<?php

// Composer: "fzaninotto/faker": "v1.3.0"
use Faker\Factory as Faker;

class CountriesTableSeeder extends Seeder {

	public function run()
	{
	Country::create(array('name'=>'Afghanistan', 'alpha_2'=>'af', 'alpha_3'=>'afg'));
    Country::create(array('name'=>'Aland Islands', 'alpha_2'=>'ax', 'alpha_3'=>'ala'));
    Country::create(array('name'=>'Albania', 'alpha_2'=>'al', 'alpha_3'=>'alb'));
    Country::create(array('name'=>'Algeria', 'alpha_2'=>'dz', 'alpha_3'=>'dza'));
    Country::create(array('name'=>'American Samoa', 'alpha_2'=>'as', 'alpha_3'=>'asm'));
    Country::create(array('name'=>'Andorra', 'alpha_2'=>'ad', 'alpha_3'=>'and'));
    Country::create(array('name'=>'Angola', 'alpha_2'=>'ao', 'alpha_3'=>'ago'));
    Country::create(array('name'=>'Anguilla', 'alpha_2'=>'ai', 'alpha_3'=>'aia'));
    Country::create(array('name'=>'Antarctica', 'alpha_2'=>'aq', 'alpha_3'=>'aqt'));
    Country::create(array('name'=>'Antigua and Barbuda', 'alpha_2'=>'ag', 'alpha_3'=>'atg'));
    Country::create(array('name'=>'Argentina', 'alpha_2'=>'ar', 'alpha_3'=>'arg'));
    Country::create(array('name'=>'Armenia', 'alpha_2'=>'am', 'alpha_3'=>'arm'));
    Country::create(array('name'=>'Aruba', 'alpha_2'=>'aw', 'alpha_3'=>'abw'));
    Country::create(array('name'=>'Australia', 'alpha_2'=>'au', 'alpha_3'=>'aus'));
    Country::create(array('name'=>'Austria', 'alpha_2'=>'at', 'alpha_3'=>'aut'));
    Country::create(array('name'=>'Azerbaijan', 'alpha_2'=>'az', 'alpha_3'=>'aze'));
    Country::create(array('name'=>'Bahamas', 'alpha_2'=>'bs', 'alpha_3'=>'bhs'));
    Country::create(array('name'=>'Bahrain', 'alpha_2'=>'bh', 'alpha_3'=>'bhr'));
    Country::create(array('name'=>'Bangladesh', 'alpha_2'=>'bd', 'alpha_3'=>'bgd'));
    Country::create(array('name'=>'Barbados', 'alpha_2'=>'bb', 'alpha_3'=>'brb'));
    Country::create(array('name'=>'Belarus', 'alpha_2'=>'by', 'alpha_3'=>'blr'));
    Country::create(array('name'=>'Belgium', 'alpha_2'=>'be', 'alpha_3'=>'bel'));
    Country::create(array('name'=>'Belize', 'alpha_2'=>'bz', 'alpha_3'=>'blz'));
    Country::create(array('name'=>'Benin', 'alpha_2'=>'bj', 'alpha_3'=>'ben'));
    Country::create(array('name'=>'Bermuda', 'alpha_2'=>'bm', 'alpha_3'=>'bmu'));
    Country::create(array('name'=>'Bhutan', 'alpha_2'=>'bt', 'alpha_3'=>'btn'));
    Country::create(array('name'=>'Bolivia, Plurinational State of', 'alpha_2'=>'bo', 'alpha_3'=>'bol'));
    Country::create(array('name'=>'Bonaire, Sint Eustatius and Saba', 'alpha_2'=>'bq', 'alpha_3'=>'bes'));
    Country::create(array('name'=>'Bosnia and Herzegovina', 'alpha_2'=>'ba', 'alpha_3'=>'bih'));
    Country::create(array('name'=>'Botswana', 'alpha_2'=>'bw', 'alpha_3'=>'bwa'));
    Country::create(array('name'=>'Bouvet Island', 'alpha_2'=>'bv', 'alpha_3'=>'bvi'));
    Country::create(array('name'=>'Brazil', 'alpha_2'=>'br', 'alpha_3'=>'bra'));
    Country::create(array('name'=>'British Indian Ocean Territory', 'alpha_2'=>'io', 'alpha_3'=>'iot'));
    Country::create(array('name'=>'Brunei Darussalam', 'alpha_2'=>'bn', 'alpha_3'=>'brn'));
    Country::create(array('name'=>'Bulgaria', 'alpha_2'=>'bg', 'alpha_3'=>'bgr'));
    Country::create(array('name'=>'Burkina Faso', 'alpha_2'=>'bf', 'alpha_3'=>'bfa'));
    Country::create(array('name'=>'Burundi', 'alpha_2'=>'bi', 'alpha_3'=>'bdi'));
    Country::create(array('name'=>'Cambodia', 'alpha_2'=>'kh', 'alpha_3'=>'khm'));
    Country::create(array('name'=>'Cameroon', 'alpha_2'=>'cm', 'alpha_3'=>'cmr'));
    Country::create(array('name'=>'Canada', 'alpha_2'=>'ca', 'alpha_3'=>'can'));
    Country::create(array('name'=>'Cape Verde', 'alpha_2'=>'cv', 'alpha_3'=>'cpv'));
    Country::create(array('name'=>'Cayman Islands', 'alpha_2'=>'ky', 'alpha_3'=>'cym'));
    Country::create(array('name'=>'Central African Republic', 'alpha_2'=>'cf', 'alpha_3'=>'caf'));
    Country::create(array('name'=>'Chad', 'alpha_2'=>'td', 'alpha_3'=>'tcd'));
    Country::create(array('name'=>'Chile', 'alpha_2'=>'cl', 'alpha_3'=>'chl'));
    Country::create(array('name'=>'China', 'alpha_2'=>'cn', 'alpha_3'=>'chn'));
    Country::create(array('name'=>'Christmas Island', 'alpha_2'=>'cx', 'alpha_3'=>'cxi'));
    Country::create(array('name'=>'Cocos (Keeling) Islands', 'alpha_2'=>'cc', 'alpha_3'=>'cci'));
    Country::create(array('name'=>'Colombia', 'alpha_2'=>'co', 'alpha_3'=>'col'));
    Country::create(array('name'=>'Comoros', 'alpha_2'=>'km', 'alpha_3'=>'com'));
    Country::create(array('name'=>'Congo', 'alpha_2'=>'cg', 'alpha_3'=>'cog'));
    Country::create(array('name'=>'Congo, The Democratic Republic of the', 'alpha_2'=>'cd', 'alpha_3'=>'cod'));
    Country::create(array('name'=>'Cook Islands', 'alpha_2'=>'ck', 'alpha_3'=>'cok'));
    Country::create(array('name'=>'Costa Rica', 'alpha_2'=>'cr', 'alpha_3'=>'cri'));
    Country::create(array('name'=>'Cote d\'Ivoire', 'alpha_2'=>'ci', 'alpha_3'=>'civ'));
    Country::create(array('name'=>'Croatia', 'alpha_2'=>'hr', 'alpha_3'=>'hrv'));
    Country::create(array('name'=>'Cuba', 'alpha_2'=>'cu', 'alpha_3'=>'cub'));
    Country::create(array('name'=>'Curacao', 'alpha_2'=>'cw', 'alpha_3'=>'cuw'));
    Country::create(array('name'=>'Cyprus', 'alpha_2'=>'cy', 'alpha_3'=>'cyp'));
    Country::create(array('name'=>'Czech Republic', 'alpha_2'=>'cz', 'alpha_3'=>'cze'));
    Country::create(array('name'=>'Denmark', 'alpha_2'=>'dk', 'alpha_3'=>'dnk'));
    Country::create(array('name'=>'Djibouti', 'alpha_2'=>'dj', 'alpha_3'=>'dji'));
    Country::create(array('name'=>'Dominica', 'alpha_2'=>'dm', 'alpha_3'=>'dma'));
    Country::create(array('name'=>'Dominican Republic', 'alpha_2'=>'do', 'alpha_3'=>'dom'));
    Country::create(array('name'=>'Ecuador', 'alpha_2'=>'ec', 'alpha_3'=>'ecu'));
    Country::create(array('name'=>'Egypt', 'alpha_2'=>'eg', 'alpha_3'=>'egy'));
    Country::create(array('name'=>'El Salvador', 'alpha_2'=>'sv', 'alpha_3'=>'slv'));
    Country::create(array('name'=>'Equatorial Guinea', 'alpha_2'=>'gq', 'alpha_3'=>'gnq'));
    Country::create(array('name'=>'Eritrea', 'alpha_2'=>'er', 'alpha_3'=>'eri'));
    Country::create(array('name'=>'Estonia', 'alpha_2'=>'ee', 'alpha_3'=>'est'));
    Country::create(array('name'=>'Ethiopia', 'alpha_2'=>'et', 'alpha_3'=>'eth'));
    Country::create(array('name'=>'Falkland Islands (Malvinas)', 'alpha_2'=>'fk', 'alpha_3'=>'flk'));
    Country::create(array('name'=>'Faroe Islands', 'alpha_2'=>'fo', 'alpha_3'=>'fro'));
    Country::create(array('name'=>'Fiji', 'alpha_2'=>'fj', 'alpha_3'=>'fji'));
    Country::create(array('name'=>'Finland', 'alpha_2'=>'fi', 'alpha_3'=>'fin'));
    Country::create(array('name'=>'France', 'alpha_2'=>'fr', 'alpha_3'=>'fra'));
    Country::create(array('name'=>'French Guiana', 'alpha_2'=>'gf', 'alpha_3'=>'guf'));
    Country::create(array('name'=>'French Polynesia', 'alpha_2'=>'pf', 'alpha_3'=>'pyf'));
    Country::create(array('name'=>'French Southern Territories', 'alpha_2'=>'tf', 'alpha_3'=>'tft'));
    Country::create(array('name'=>'Gabon', 'alpha_2'=>'ga', 'alpha_3'=>'gab'));
    Country::create(array('name'=>'Gambia', 'alpha_2'=>'gm', 'alpha_3'=>'gmb'));
    Country::create(array('name'=>'Georgia', 'alpha_2'=>'ge', 'alpha_3'=>'geo'));
    Country::create(array('name'=>'Germany', 'alpha_2'=>'de', 'alpha_3'=>'deu'));
    Country::create(array('name'=>'Ghana', 'alpha_2'=>'gh', 'alpha_3'=>'gha'));
    Country::create(array('name'=>'Gibraltar', 'alpha_2'=>'gi', 'alpha_3'=>'gib'));
    Country::create(array('name'=>'Greece', 'alpha_2'=>'gr', 'alpha_3'=>'grc'));
    Country::create(array('name'=>'Greenland', 'alpha_2'=>'gl', 'alpha_3'=>'grl'));
    Country::create(array('name'=>'Grenada', 'alpha_2'=>'gd', 'alpha_3'=>'grd'));
    Country::create(array('name'=>'Guadeloupe', 'alpha_2'=>'gp', 'alpha_3'=>'glp'));
    Country::create(array('name'=>'Guam', 'alpha_2'=>'gu', 'alpha_3'=>'gum'));
    Country::create(array('name'=>'Guatemala', 'alpha_2'=>'gt', 'alpha_3'=>'gtm'));
    Country::create(array('name'=>'Guernsey', 'alpha_2'=>'gg', 'alpha_3'=>'ggy'));
    Country::create(array('name'=>'Guinea', 'alpha_2'=>'gn', 'alpha_3'=>'gin'));
    Country::create(array('name'=>'Guinea-Bissau', 'alpha_2'=>'gw', 'alpha_3'=>'gnb'));
    Country::create(array('name'=>'Guyana', 'alpha_2'=>'gy', 'alpha_3'=>'guy'));
    Country::create(array('name'=>'Haiti', 'alpha_2'=>'ht', 'alpha_3'=>'hti'));
    Country::create(array('name'=>'Heard Island and McDonald Islands', 'alpha_2'=>'hm', 'alpha_3'=>'hmi'));
    Country::create(array('name'=>'Holy See (Vatican City State)', 'alpha_2'=>'va', 'alpha_3'=>'vat'));
    Country::create(array('name'=>'Honduras', 'alpha_2'=>'hn', 'alpha_3'=>'hnd'));
    Country::create(array('name'=>'Hong Kong', 'alpha_2'=>'hk', 'alpha_3'=>'hkg'));
    Country::create(array('name'=>'Hungary', 'alpha_2'=>'hu', 'alpha_3'=>'hun'));
    Country::create(array('name'=>'Iceland', 'alpha_2'=>'is', 'alpha_3'=>'isl'));
    Country::create(array('name'=>'India', 'alpha_2'=>'in', 'alpha_3'=>'ind'));
    Country::create(array('name'=>'Indonesia', 'alpha_2'=>'id', 'alpha_3'=>'idn'));
    Country::create(array('name'=>'Iran, Islamic Republic of', 'alpha_2'=>'ir', 'alpha_3'=>'irn'));
    Country::create(array('name'=>'Iraq', 'alpha_2'=>'iq', 'alpha_3'=>'irq'));
    Country::create(array('name'=>'Ireland', 'alpha_2'=>'ie', 'alpha_3'=>'irl'));
    Country::create(array('name'=>'Isle of Man', 'alpha_2'=>'im', 'alpha_3'=>'imn'));
    Country::create(array('name'=>'Israel', 'alpha_2'=>'il', 'alpha_3'=>'isr'));
    Country::create(array('name'=>'Italy', 'alpha_2'=>'it', 'alpha_3'=>'ita'));
    Country::create(array('name'=>'Jamaica', 'alpha_2'=>'jm', 'alpha_3'=>'jam'));
    Country::create(array('name'=>'Japan', 'alpha_2'=>'jp', 'alpha_3'=>'jpn'));
    Country::create(array('name'=>'Jersey', 'alpha_2'=>'je', 'alpha_3'=>'jey'));
    Country::create(array('name'=>'Jordan', 'alpha_2'=>'jo', 'alpha_3'=>'jor'));
    Country::create(array('name'=>'Kazakhstan', 'alpha_2'=>'kz', 'alpha_3'=>'kaz'));
    Country::create(array('name'=>'Kenya', 'alpha_2'=>'ke', 'alpha_3'=>'ken'));
    Country::create(array('name'=>'Kiribati', 'alpha_2'=>'ki', 'alpha_3'=>'kir'));
    Country::create(array('name'=>'Korea, Democratic People\'s Republic of', 'alpha_2'=>'kp', 'alpha_3'=>'prk'));
    Country::create(array('name'=>'Korea, Republic of', 'alpha_2'=>'kr', 'alpha_3'=>'kor'));
    Country::create(array('name'=>'Kuwait', 'alpha_2'=>'kw', 'alpha_3'=>'kwt'));
    Country::create(array('name'=>'Kyrgyzstan', 'alpha_2'=>'kg', 'alpha_3'=>'kgz'));
    Country::create(array('name'=>'Lao People\'s Democratic Republic', 'alpha_2'=>'la', 'alpha_3'=>'lao'));
    Country::create(array('name'=>'Latvia', 'alpha_2'=>'lv', 'alpha_3'=>'lva'));
    Country::create(array('name'=>'Lebanon', 'alpha_2'=>'lb', 'alpha_3'=>'lbn'));
    Country::create(array('name'=>'Lesotho', 'alpha_2'=>'ls', 'alpha_3'=>'lso'));
    Country::create(array('name'=>'Liberia', 'alpha_2'=>'lr', 'alpha_3'=>'lbr'));
    Country::create(array('name'=>'Libyan Arab Jamahiriya', 'alpha_2'=>'ly', 'alpha_3'=>'lby'));
    Country::create(array('name'=>'Liechtenstein', 'alpha_2'=>'li', 'alpha_3'=>'lie'));
    Country::create(array('name'=>'Lithuania', 'alpha_2'=>'lt', 'alpha_3'=>'ltu'));
    Country::create(array('name'=>'Luxembourg', 'alpha_2'=>'lu', 'alpha_3'=>'lux'));
    Country::create(array('name'=>'Macao', 'alpha_2'=>'mo', 'alpha_3'=>'mac'));
    Country::create(array('name'=>'Macedonia, The former Yugoslav Republic of', 'alpha_2'=>'mk', 'alpha_3'=>'mkd'));
    Country::create(array('name'=>'Madagascar', 'alpha_2'=>'mg', 'alpha_3'=>'mdg'));
    Country::create(array('name'=>'Malawi', 'alpha_2'=>'mw', 'alpha_3'=>'mwi'));
    Country::create(array('name'=>'Malaysia', 'alpha_2'=>'my', 'alpha_3'=>'mys'));
    Country::create(array('name'=>'Maldives', 'alpha_2'=>'mv', 'alpha_3'=>'mdv'));
    Country::create(array('name'=>'Mali', 'alpha_2'=>'ml', 'alpha_3'=>'mli'));
    Country::create(array('name'=>'Malta', 'alpha_2'=>'mt', 'alpha_3'=>'mlt'));
    Country::create(array('name'=>'Marshall Islands', 'alpha_2'=>'mh', 'alpha_3'=>'mhl'));
    Country::create(array('name'=>'Martinique', 'alpha_2'=>'mq', 'alpha_3'=>'mtq'));
    Country::create(array('name'=>'Mauritania', 'alpha_2'=>'mr', 'alpha_3'=>'mrt'));
    Country::create(array('name'=>'Mauritius', 'alpha_2'=>'mu', 'alpha_3'=>'mus'));
    Country::create(array('name'=>'Mayotte', 'alpha_2'=>'yt', 'alpha_3'=>'myt'));
    Country::create(array('name'=>'Mexico', 'alpha_2'=>'mx', 'alpha_3'=>'mex'));
    Country::create(array('name'=>'Micronesia, Federated States of', 'alpha_2'=>'fm', 'alpha_3'=>'fsm'));
    Country::create(array('name'=>'Moldova, Republic of', 'alpha_2'=>'md', 'alpha_3'=>'mda'));
    Country::create(array('name'=>'Monaco', 'alpha_2'=>'mc', 'alpha_3'=>'mco'));
    Country::create(array('name'=>'Mongolia', 'alpha_2'=>'mn', 'alpha_3'=>'mng'));
    Country::create(array('name'=>'Montenegro', 'alpha_2'=>'me', 'alpha_3'=>'mne'));
    Country::create(array('name'=>'Montserrat', 'alpha_2'=>'ms', 'alpha_3'=>'msr'));
    Country::create(array('name'=>'Morocco', 'alpha_2'=>'ma', 'alpha_3'=>'mar'));
    Country::create(array('name'=>'Mozambique', 'alpha_2'=>'mz', 'alpha_3'=>'moz'));
    Country::create(array('name'=>'Myanmar', 'alpha_2'=>'mm', 'alpha_3'=>'mmr'));
    Country::create(array('name'=>'Namibia', 'alpha_2'=>'na', 'alpha_3'=>'nam'));
    Country::create(array('name'=>'Nauru', 'alpha_2'=>'nr', 'alpha_3'=>'nru'));
    Country::create(array('name'=>'Nepal', 'alpha_2'=>'np', 'alpha_3'=>'npl'));
    Country::create(array('name'=>'Netherlands', 'alpha_2'=>'nl', 'alpha_3'=>'nld'));
    Country::create(array('name'=>'New Caledonia', 'alpha_2'=>'nc', 'alpha_3'=>'ncl'));
    Country::create(array('name'=>'New Zealand', 'alpha_2'=>'nz', 'alpha_3'=>'nzl'));
    Country::create(array('name'=>'Nicaragua', 'alpha_2'=>'ni', 'alpha_3'=>'nic'));
    Country::create(array('name'=>'Niger', 'alpha_2'=>'ne', 'alpha_3'=>'ner'));
    Country::create(array('name'=>'Nigeria', 'alpha_2'=>'ng', 'alpha_3'=>'nga'));
    Country::create(array('name'=>'Niue', 'alpha_2'=>'nu', 'alpha_3'=>'niu'));
    Country::create(array('name'=>'Norfolk Island', 'alpha_2'=>'nf', 'alpha_3'=>'nfk'));
    Country::create(array('name'=>'Northern Mariana Islands', 'alpha_2'=>'mp', 'alpha_3'=>'mnp'));
    Country::create(array('name'=>'Norway', 'alpha_2'=>'no', 'alpha_3'=>'nor'));
    Country::create(array('name'=>'Oman', 'alpha_2'=>'om', 'alpha_3'=>'omn'));
    Country::create(array('name'=>'Pakistan', 'alpha_2'=>'pk', 'alpha_3'=>'pak'));
    Country::create(array('name'=>'Palau', 'alpha_2'=>'pw', 'alpha_3'=>'plw'));
    Country::create(array('name'=>'Palestinian Territory, Occupied', 'alpha_2'=>'ps', 'alpha_3'=>'pse'));
    Country::create(array('name'=>'Panama', 'alpha_2'=>'pa', 'alpha_3'=>'pan'));
    Country::create(array('name'=>'Papua New Guinea', 'alpha_2'=>'pg', 'alpha_3'=>'png'));
    Country::create(array('name'=>'Paraguay', 'alpha_2'=>'py', 'alpha_3'=>'pry'));
    Country::create(array('name'=>'Peru', 'alpha_2'=>'pe', 'alpha_3'=>'per'));
    Country::create(array('name'=>'Philippines', 'alpha_2'=>'ph', 'alpha_3'=>'phl'));
    Country::create(array('name'=>'Pitcairn', 'alpha_2'=>'pn', 'alpha_3'=>'pcn'));
    Country::create(array('name'=>'Poland', 'alpha_2'=>'pl', 'alpha_3'=>'pol'));
    Country::create(array('name'=>'Portugal', 'alpha_2'=>'pt', 'alpha_3'=>'prt'));
    Country::create(array('name'=>'Puerto Rico', 'alpha_2'=>'pr', 'alpha_3'=>'pri'));
    Country::create(array('name'=>'Qatar', 'alpha_2'=>'qa', 'alpha_3'=>'qat'));
    Country::create(array('name'=>'Reunion', 'alpha_2'=>'re', 'alpha_3'=>'reu'));
    Country::create(array('name'=>'Romania', 'alpha_2'=>'ro', 'alpha_3'=>'rou'));
    Country::create(array('name'=>'Russian Federation', 'alpha_2'=>'ru', 'alpha_3'=>'rus'));
    Country::create(array('name'=>'Rwanda', 'alpha_2'=>'rw', 'alpha_3'=>'rwa'));
    Country::create(array('name'=>'Saint Barthelemy', 'alpha_2'=>'bl', 'alpha_3'=>'blm'));
    Country::create(array('name'=>'Saint Helena, Ascension and Tristan Da Cunha', 'alpha_2'=>'sh', 'alpha_3'=>'shn'));
    Country::create(array('name'=>'Saint Kitts and Nevis', 'alpha_2'=>'kn', 'alpha_3'=>'kna'));
    Country::create(array('name'=>'Saint Lucia', 'alpha_2'=>'lc', 'alpha_3'=>'lca'));
    Country::create(array('name'=>'Saint Martin (French Part)', 'alpha_2'=>'mf', 'alpha_3'=>'maf'));
    Country::create(array('name'=>'Saint Pierre and Miquelon', 'alpha_2'=>'pm', 'alpha_3'=>'spm'));
    Country::create(array('name'=>'Saint Vincent and The Grenadines', 'alpha_2'=>'vc', 'alpha_3'=>'vct'));
    Country::create(array('name'=>'Samoa', 'alpha_2'=>'ws', 'alpha_3'=>'wsm'));
    Country::create(array('name'=>'San Marino', 'alpha_2'=>'sm', 'alpha_3'=>'smr'));
    Country::create(array('name'=>'Sao Tome and Principe', 'alpha_2'=>'st', 'alpha_3'=>'stp'));
    Country::create(array('name'=>'Saudi Arabia', 'alpha_2'=>'sa', 'alpha_3'=>'sau'));
    Country::create(array('name'=>'Senegal', 'alpha_2'=>'sn', 'alpha_3'=>'sen'));
    Country::create(array('name'=>'Serbia', 'alpha_2'=>'rs', 'alpha_3'=>'srb'));
    Country::create(array('name'=>'Seychelles', 'alpha_2'=>'sc', 'alpha_3'=>'syc'));
    Country::create(array('name'=>'Sierra Leone', 'alpha_2'=>'sl', 'alpha_3'=>'sle'));
    Country::create(array('name'=>'Singapore', 'alpha_2'=>'sg', 'alpha_3'=>'sgp'));
    Country::create(array('name'=>'Sint Maarten (Dutch Part)', 'alpha_2'=>'sx', 'alpha_3'=>'sxm'));
    Country::create(array('name'=>'Slovakia', 'alpha_2'=>'sk', 'alpha_3'=>'svk'));
    Country::create(array('name'=>'Slovenia', 'alpha_2'=>'si', 'alpha_3'=>'svn'));
    Country::create(array('name'=>'Solomon Islands', 'alpha_2'=>'sb', 'alpha_3'=>'slb'));
    Country::create(array('name'=>'Somalia', 'alpha_2'=>'so', 'alpha_3'=>'som'));
    Country::create(array('name'=>'South Africa', 'alpha_2'=>'za', 'alpha_3'=>'zaf'));
    Country::create(array('name'=>'South Georgia and The South Sandwich Islands', 'alpha_2'=>'gs', 'alpha_3'=>'gsi'));
    Country::create(array('name'=>'South Sudan', 'alpha_2'=>'ss', 'alpha_3'=>'ssd'));
    Country::create(array('name'=>'Spain', 'alpha_2'=>'es', 'alpha_3'=>'esp'));
    Country::create(array('name'=>'Sri Lanka', 'alpha_2'=>'lk', 'alpha_3'=>'lka'));
    Country::create(array('name'=>'Sudan', 'alpha_2'=>'sd', 'alpha_3'=>'sdn'));
    Country::create(array('name'=>'Suriname', 'alpha_2'=>'sr', 'alpha_3'=>'sur'));
    Country::create(array('name'=>'Svalbard and Jan Mayen', 'alpha_2'=>'sj', 'alpha_3'=>'sjm'));
    Country::create(array('name'=>'Swaziland', 'alpha_2'=>'sz', 'alpha_3'=>'swz'));
    Country::create(array('name'=>'Sweden', 'alpha_2'=>'se', 'alpha_3'=>'swe'));
    Country::create(array('name'=>'Switzerland', 'alpha_2'=>'ch', 'alpha_3'=>'che'));
    Country::create(array('name'=>'Syrian Arab Republic', 'alpha_2'=>'sy', 'alpha_3'=>'syr'));
    Country::create(array('name'=>'Taiwan, Province of China', 'alpha_2'=>'tw', 'alpha_3'=>'twc'));
    Country::create(array('name'=>'Tajikistan', 'alpha_2'=>'tj', 'alpha_3'=>'tjk'));
    Country::create(array('name'=>'Tanzania, United Republic of', 'alpha_2'=>'tz', 'alpha_3'=>'tza'));
    Country::create(array('name'=>'Thailand', 'alpha_2'=>'th', 'alpha_3'=>'tha'));
    Country::create(array('name'=>'Timor-Leste', 'alpha_2'=>'tl', 'alpha_3'=>'tls'));
    Country::create(array('name'=>'Togo', 'alpha_2'=>'tg', 'alpha_3'=>'tgo'));
    Country::create(array('name'=>'Tokelau', 'alpha_2'=>'tk', 'alpha_3'=>'tkl'));
    Country::create(array('name'=>'Tonga', 'alpha_2'=>'to', 'alpha_3'=>'ton'));
    Country::create(array('name'=>'Trinidad and Tobago', 'alpha_2'=>'tt', 'alpha_3'=>'tto'));
    Country::create(array('name'=>'Tunisia', 'alpha_2'=>'tn', 'alpha_3'=>'tun'));
    Country::create(array('name'=>'Turkey', 'alpha_2'=>'tr', 'alpha_3'=>'tur'));
    Country::create(array('name'=>'Turkmenistan', 'alpha_2'=>'tm', 'alpha_3'=>'tkm'));
    Country::create(array('name'=>'Turks and Caicos Islands', 'alpha_2'=>'tc', 'alpha_3'=>'tca'));
    Country::create(array('name'=>'Tuvalu', 'alpha_2'=>'tv', 'alpha_3'=>'tuv'));
    Country::create(array('name'=>'Uganda', 'alpha_2'=>'ug', 'alpha_3'=>'uga'));
    Country::create(array('name'=>'Ukraine', 'alpha_2'=>'ua', 'alpha_3'=>'ukr'));
    Country::create(array('name'=>'United Arab Emirates', 'alpha_2'=>'ae', 'alpha_3'=>'are'));
    Country::create(array('name'=>'United Kingdom', 'alpha_2'=>'gb', 'alpha_3'=>'gbr'));
    Country::create(array('name'=>'United States', 'alpha_2'=>'us', 'alpha_3'=>'usa'));
    Country::create(array('name'=>'United States Minor Outlying Islands', 'alpha_2'=>'um', 'alpha_3'=>'umi'));
    Country::create(array('name'=>'Uruguay', 'alpha_2'=>'uy', 'alpha_3'=>'ury'));
    Country::create(array('name'=>'Uzbekistan', 'alpha_2'=>'uz', 'alpha_3'=>'uzb'));
    Country::create(array('name'=>'Vanuatu', 'alpha_2'=>'vu', 'alpha_3'=>'vut'));
    Country::create(array('name'=>'Venezuela, Bolivarian Republic of', 'alpha_2'=>'ve', 'alpha_3'=>'ven'));
    Country::create(array('name'=>'Viet Nam', 'alpha_2'=>'vn', 'alpha_3'=>'vnm'));
    Country::create(array('name'=>'Virgin Islands, British', 'alpha_2'=>'vg', 'alpha_3'=>'vgb'));
    Country::create(array('name'=>'Virgin Islands, U.S.', 'alpha_2'=>'vi', 'alpha_3'=>'vir'));
    Country::create(array('name'=>'Wallis and Futuna', 'alpha_2'=>'wf', 'alpha_3'=>'wlf'));
    Country::create(array('name'=>'Western Sahara', 'alpha_2'=>'eh', 'alpha_3'=>'esh'));
    Country::create(array('name'=>'Yemen', 'alpha_2'=>'ye', 'alpha_3'=>'yem'));
    Country::create(array('name'=>'Zambia', 'alpha_2'=>'zm', 'alpha_3'=>'zmb'));
    Country::create(array('name'=>'Zimbabwe', 'alpha_2'=>'zw', 'alpha_3'=>'zwe'));
	}

}